scalar DateTime

type Query {
    me: User
    user(id: ID!): User
    post(id: ID!): Post
    feed(limit: Int! = 20, offset: Int! = 0): [Post!]!
}

type Mutation {
    createPost(input: CreatePostInput!): Post!
    deletePost(id: ID!): Boolean!
}

type User {
    id: ID!
    username: String!
    displayName: String!
    bio: String
    createdAt: DateTime!
    posts(limit: Int! = 20, offset: Int! = 0): [Post!]!
    followerCount: Int!
    followingCount: Int!
}

type Post {
    id: ID!
    content: String!
    author: User!
    createdAt: DateTime!
    likeCount: Int!
    commentCount: Int!
}

input CreatePostInput {
    content: String!
}
